version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: marketplace_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Marketplace.Api/Dockerfile.dev
    container_name: marketplace_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=marketplace;Username=postgres;Password=postgres
      - Jwt__Key=o3f1E1//UQjdW5G+Vz0QBuV0VPlWjvemtK5EcH6nOpw=
      - Jwt__Issuer=Marketplace
      - Jwt__Audience=MarketplaceUsers
    volumes:
      - ./backend/Marketplace.Api:/app/Marketplace.Api
      - ./backend/Marketplace.Application:/app/Marketplace.Application
      - ./backend/Marketplace.Infrastructure:/app/Marketplace.Infrastructure
      - ./backend/Marketplace.Core:/app/Marketplace.Core
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
