@url = http://localhost:5000
# @url = https://secondhandmarket-iskc.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjE1NTdiNzVhLTU5ODQtNDRmNy1iM2Y4LTk4Y2IyNjg3NjRkYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IlRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTc3NjY5NjgyNSwiaXNzIjoiTWFya2V0cGxhY2UiLCJhdWQiOiJNYXJrZXRwbGFjZVVzZXJzIn0.C1P_8Fnah9pjjvB6jfptlhy_KDyDAJVtQICRh8Rrc94
@listing_id = f71c0a3f-703b-4fd8-a7f7-58ce1d29d2cc

###
GET {{url}}/api/health

###
POST {{url}}/api/auth/register
Content-Type: application/json

{
    "Email": "Test1@gmail.com",
    "Password": "Test"
}

###
POST {{url}}/api/auth/login
Content-Type: application/json

{
    "Email": "Test1@gmail.com",
    "Password": "Test"
}

###
POST {{url}}/api/listings
Authorization: Bearer {{token}}

###
PUT {{url}}/api/listings/{{listing_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Title": "Sofa",
    "Description": "Brand new Ikea sofa",
    "Price": 150,
    "Latitude": 23.5,
    "Longitude": 15,
    "CoverImageUrl": "https://res.cloudinary.com/dis7dwqvp/image/upload/v1776693352/cyp2ayhzhn6shbfh5dqk.png"
}

###
PUT {{url}}/api/listings/{{listing_id}}/publish
Authorization: Bearer {{token}}

###
POST {{url}}/api/listings/{{listing_id}}/images
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="cake2.png"
Content-Type: image/png

< ./cake.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET {{url}}/api/listings

###
GET {{url}}/api/listings?latitude=23.4&longitude=15.209900&radiusKm=500