@url = http://localhost:5000
# @url = https://secondhandmarket-iskc.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3NGVkZmQ5LTFiNDMtNDEyZC05ZTRmLThiM2JjNWY5N2E5YSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IlRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTc3NjA3MTA2MywiaXNzIjoiTWFya2V0cGxhY2UiLCJhdWQiOiJNYXJrZXRwbGFjZVVzZXJzIn0.qKTP6kyoBj6ISwxUp1N0mQ-XdeOA6W4KTYsd02uxXcI
@listing_id = a7896142-daa6-415f-b188-48dff55daf43

###
GET {{url}}/api/health

###
POST {{url}}/api/auth/register
Content-Type: application/json

{
    "Email": "Test1@gmail.com",
    "Password": "Test"
}

###
POST {{url}}/api/auth/login
Content-Type: application/json

{
    "Email": "Test1@gmail.com",
    "Password": "Test"
}

###
POST {{url}}/api/listings
Authorization: Bearer {{token}}

###
PUT {{url}}/api/listings
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Title": "Sofa",
    "Description": "Brand new Ikea sofa",
    "Price": 150,
    "Latitude": 23.5,
    "Longitude": 15
}

###
POST {{url}}/api/listings/{{listing_id}}/images
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="cake.png"
Content-Type: image/png

< ./cake.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET {{url}}/api/listings?latitude=23.4&longitude=15.209900&radiusKm=500