FROM mcr.microsoft.com/dotnet/sdk:10.0 AS dev
WORKDIR /app

# Optional: clean any leftover compiled files
RUN rm -rf Marketplace.Api/bin Marketplace.Api/obj

# Expose port
EXPOSE 8080

# Set default entrypoint for hot reload
ENTRYPOINT ["dotnet", "watch", "run", "--project", "Marketplace.Api/Marketplace.Api.csproj", "--urls", "http://+:8080"]